package org.jghill.timelinevisualizersourcesgui;

/**
 * A panel for containing collecting information about new SPARQL endpoints.
 * 
 * @author JGHill
 */
public class SPARQLEndpointPanel extends javax.swing.JPanel {

    /**
     * Creates new form SPARQLEndpointPanel
     */
    public SPARQLEndpointPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DescriptionText = new javax.swing.JLabel();
        WebAddressTextField = new javax.swing.JTextField();
        CIDOCText = new javax.swing.JLabel();
        CIDOCTextField = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(360, 120));
        setMinimumSize(new java.awt.Dimension(360, 120));
        setName("SPARQLpanel"); // NOI18N
        setPreferredSize(new java.awt.Dimension(360, 120));

        org.openide.awt.Mnemonics.setLocalizedText(DescriptionText, org.openide.util.NbBundle.getMessage(SPARQLEndpointPanel.class, "SPARQLEndpointPanel.DescriptionText.text")); // NOI18N

        WebAddressTextField.setText(org.openide.util.NbBundle.getMessage(SPARQLEndpointPanel.class, "SPARQLEndpointPanel.WebAddressTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(CIDOCText, org.openide.util.NbBundle.getMessage(SPARQLEndpointPanel.class, "SPARQLEndpointPanel.CIDOCText.text")); // NOI18N

        CIDOCTextField.setText(org.openide.util.NbBundle.getMessage(SPARQLEndpointPanel.class, "SPARQLEndpointPanel.CIDOCTextField.text")); // NOI18N
        CIDOCTextField.setToolTipText(org.openide.util.NbBundle.getMessage(SPARQLEndpointPanel.class, "SPARQLEndpointPanel.CIDOCTextField.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WebAddressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(CIDOCText)
                    .addComponent(CIDOCTextField))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DescriptionText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WebAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CIDOCText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CIDOCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CIDOCText;
    private javax.swing.JTextField CIDOCTextField;
    private javax.swing.JLabel DescriptionText;
    private javax.swing.JTextField WebAddressTextField;
    // End of variables declaration//GEN-END:variables

    /**
     * Returns the text entered into the web address text field unless there
     * is no text, in which case a null is returned.
     * 
     * @return text entered into the text field or a null.
     */
    public String getAddressText() {
        String webAddress;
        try {
            webAddress = WebAddressTextField.getText();
            return webAddress;
        } catch (NullPointerException e) {
            return null;
        }
    }
    
    /**
     * Sets the web address text to the passed string.
     * 
     * @param webAddress a web address.
     */
    public void setAddressText(String webAddress) {
        WebAddressTextField.setText(webAddress);
    }
    
    /**
     * Returns the CIDOC CRM address entered into the text field.
     * 
     * @return the text or a null if there is no text.
     */
    public String getCIDOCText() {
        String cidocText;
        try {
            cidocText = CIDOCTextField.getText();
            return cidocText;
        } catch (NullPointerException e) {
            return null;
        }
    }
    
    /**
     * Sets the CIDOC CRM text to the passed string.
     * 
     * @param cidocText a CIDOC CRM address.
     */
    public void setCIDOCText(String cidocText) {
        CIDOCTextField.setText(cidocText);
    }
    
}