package org.jghill.timelinevisualizersourcesgui;

/**
 * A panel for containing collecting information about new SPARQL endpoints.
 * 
 * @author JGHill
 */
public class SPARQLEndpointPanel extends javax.swing.JPanel {

    /**
     * Creates new form SPARQLEndpointPanel
     */
    public SPARQLEndpointPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DescriptionText = new javax.swing.JLabel();
        WebAddressText = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(360, 120));
        setMinimumSize(new java.awt.Dimension(360, 120));
        setPreferredSize(new java.awt.Dimension(360, 120));

        org.openide.awt.Mnemonics.setLocalizedText(DescriptionText, org.openide.util.NbBundle.getMessage(SPARQLEndpointPanel.class, "SPARQLEndpointPanel.DescriptionText.text")); // NOI18N

        WebAddressText.setText(org.openide.util.NbBundle.getMessage(SPARQLEndpointPanel.class, "SPARQLEndpointPanel.WebAddressText.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WebAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DescriptionText)
                .addGap(18, 18, 18)
                .addComponent(WebAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DescriptionText;
    private javax.swing.JTextField WebAddressText;
    // End of variables declaration//GEN-END:variables
}