package org.jghill.timelinesvisualizercollections.gui;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;
import java.util.regex.Pattern;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import org.apache.jena.atlas.web.HttpException;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.jghill.timelinesvisualizercollections.Collection;
import org.jghill.timelinesvisualizercollections.container.CollectionContainer;
import org.jghill.timelinesvisualizercollections.display.EntityDisplay;
import org.jghill.timelinesvisualizercollections.display.TimeLine;
import org.jghill.timelinesvisualizerdispatcher.Dispatcher;
import org.jghill.timelinesvisualizerqueriesbuilder.QueryBuilder;
import org.jghill.timelinesvisualizerqueriesbuilder.QuerySettings;
import org.jghill.timelinevisualizerentities.Entities;
import org.jghill.timelinevisualizerentities.ManMadeObject;
import org.jghill.timelinevisualizerentitiescollection.EntitiesCollection;
import org.jghill.timelinevisualizerqueries.QueryShell;
import org.jghill.timelinevisualizersources.Source;
import org.jghill.timelinevisualizersources.SourceCollection;
import org.netbeans.api.io.IOProvider;
import org.netbeans.api.io.InputOutput;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.RequestProcessor;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;

/**
 * A window for displaying a collection and it's internals.
 */
@ConvertAsProperties(
        dtd = "-//org.jghill.timelinesvisualizercollectionsgui//Collection//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "CollectionTopComponent"
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "org.jghill.timelinesvisualizercollectionsgui.CollectionTopComponent")
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_CollectionAction",
        preferredID = "CollectionTopComponent"
)
@Messages({
    "CTL_CollectionAction=Collection",
    "CTL_CollectionTopComponent=Collection Window",
    "HINT_CollectionTopComponent=This is a Collection window"
})
public final class CollectionTopComponent extends TopComponent implements FocusListener {
    
    /**
     * Constructor.
     */
    public CollectionTopComponent() {
        
        Lookup tcLookup = CollectionContainer.getLookup();
        coll = tcLookup.lookup(Collection.class);
        CollectionContainer.addCollection(coll);
        
        initComponents();
        setToolTipText(Bundle.HINT_CollectionTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.FALSE);
        putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
        
        TitleTextBox.setText(coll.getName());
        qtb = (QueryTableModel) QueriesTable.getModel();
        etb = (EntityTableModel) EntitiesTable.getModel();
        
        Lookup sLookup = SourceCollection.getInstance().getLookup();
        sources = sLookup.lookupResult(Source.class);
        sources.allInstances();
        sources.addLookupListener((LookupEvent e) -> {
            SourceComboBox.setModel(
                    new DefaultComboBoxModel(
                            SourceCollection.collectionToArray()));
        });
        
        categories.add(none);
        categories.add(query);
        categories.add(source);
        categories.add(depicts);
        categories.add(material);
        categories.add(type);
        categories.add(technique);
        ComboBoxModel comboModel = new DefaultComboBoxModel(categories.toArray());
        FirstFilterComboBox.setModel(comboModel);
        FirstFilterComboBox.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tab = new javax.swing.JTabbedPane();
        Information = new javax.swing.JPanel();
        NotesTextPanel = new javax.swing.JScrollPane();
        NotesTextBox = new javax.swing.JTextArea();
        NotesText = new javax.swing.JLabel();
        TitleTextBox = new javax.swing.JTextField();
        Queries = new javax.swing.JPanel();
        QueriesScrollPane = new javax.swing.JScrollPane();
        QueriesTable = new javax.swing.JTable();
        ExistingQueriesText = new javax.swing.JLabel();
        QuerySeparator = new javax.swing.JSeparator();
        QueryBuilderText = new javax.swing.JLabel();
        CreateButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        VerticalSeparator = new javax.swing.JSeparator();
        SourceTextLabel = new javax.swing.JLabel();
        SourceComboBox = new javax.swing.JComboBox<>();
        HasNameCheckBox = new javax.swing.JCheckBox();
        HasImageCheckBox = new javax.swing.JCheckBox();
        HasIdentifierCheckBox = new javax.swing.JCheckBox();
        DeleteButton = new javax.swing.JButton();
        AndText1 = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        IdentifierTextField = new javax.swing.JTextField();
        RunButton = new javax.swing.JButton();
        HasLimitCheckBox = new javax.swing.JCheckBox();
        LimitTextField = new javax.swing.JTextField();
        SourceNameTextLabel = new javax.swing.JLabel();
        QueryNameTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        CreationYearLabel = new javax.swing.JLabel();
        CreationStartYearTextField = new javax.swing.JTextField();
        CreationEndYearTextField = new javax.swing.JTextField();
        HasDepictionCheckBox = new javax.swing.JCheckBox();
        DepictionTextField = new javax.swing.JTextField();
        HasConsistsCheckBox = new javax.swing.JCheckBox();
        MaterialTextField = new javax.swing.JTextField();
        HasTypeCheckBox = new javax.swing.JCheckBox();
        TypeTextField = new javax.swing.JTextField();
        HasTechniqueCheckBox = new javax.swing.JCheckBox();
        TechniqueTextField = new javax.swing.JTextField();
        Entities = new javax.swing.JPanel();
        EntitiesScrollPane = new javax.swing.JScrollPane();
        EntitiesTable = new javax.swing.JTable();
        Visualizer = new javax.swing.JPanel();
        FirstFilterLabel = new javax.swing.JLabel();
        FirstFilterComboBox = new javax.swing.JComboBox<>();
        Group1Label = new javax.swing.JLabel();
        Group1ComboBox = new javax.swing.JComboBox<>();
        Group1FilterLabel = new javax.swing.JLabel();
        Group1FilterComboBox = new javax.swing.JComboBox<>();
        Group2Label = new javax.swing.JLabel();
        Group2ComboBox = new javax.swing.JComboBox<>();
        Group2FilterLabel = new javax.swing.JLabel();
        Group2FilterComboBox = new javax.swing.JComboBox<>();
        collectionDisplayPanel = new org.jghill.timelinesvisualizercollections.display.CollectionDisplayPanel();

        setPreferredSize(new java.awt.Dimension(1100, 500));

        Tab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        NotesTextBox.setColumns(20);
        NotesTextBox.setRows(5);
        NotesTextPanel.setViewportView(NotesTextBox);

        org.openide.awt.Mnemonics.setLocalizedText(NotesText, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.NotesText.text")); // NOI18N

        TitleTextBox.setColumns(50);
        TitleTextBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TitleTextBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TitleTextBox.setText(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.TitleTextBox.text")); // NOI18N
        TitleTextBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TitleTextBox.setMargin(new java.awt.Insets(10, 10, 10, 10));
        TitleTextBox.setMinimumSize(new java.awt.Dimension(50, 50));
        TitleTextBox.setPreferredSize(new java.awt.Dimension(1000, 50));
        TitleTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TitleTextBoxKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout InformationLayout = new javax.swing.GroupLayout(Information);
        Information.setLayout(InformationLayout);
        InformationLayout.setHorizontalGroup(
            InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TitleTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
                    .addComponent(NotesTextPanel)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InformationLayout.createSequentialGroup()
                        .addComponent(NotesText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 855, Short.MAX_VALUE)))
                .addContainerGap())
        );
        InformationLayout.setVerticalGroup(
            InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NotesText)
                .addGap(18, 18, 18)
                .addComponent(NotesTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tab.addTab(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.Information.TabConstraints.tabTitle"), Information); // NOI18N

        QueriesScrollPane.setPreferredSize(new java.awt.Dimension(440, 400));

        QueriesTable.setAutoCreateRowSorter(true);
        QueriesTable.setModel(new QueryTableModel(coll));
        QueriesTable.setRowHeight(20);
        QueriesScrollPane.setViewportView(QueriesTable);

        org.openide.awt.Mnemonics.setLocalizedText(ExistingQueriesText, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.ExistingQueriesText.text")); // NOI18N
        ExistingQueriesText.setPreferredSize(new java.awt.Dimension(100, 14));

        QuerySeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        org.openide.awt.Mnemonics.setLocalizedText(QueryBuilderText, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.QueryBuilderText.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(CreateButton, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.CreateButton.text")); // NOI18N
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(ResetButton, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.ResetButton.text")); // NOI18N
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(SourceTextLabel, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.SourceTextLabel.text")); // NOI18N

        SourceComboBox.setModel(new DefaultComboBoxModel(SourceCollection.getInstance().collectionToArray()));

        org.openide.awt.Mnemonics.setLocalizedText(HasNameCheckBox, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.HasNameCheckBox.text")); // NOI18N
        HasNameCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasNameCheckBoxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(HasImageCheckBox, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.HasImageCheckBox.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(HasIdentifierCheckBox, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.HasIdentifierCheckBox.text")); // NOI18N
        HasIdentifierCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasIdentifierCheckBoxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(DeleteButton, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.DeleteButton.text")); // NOI18N
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(AndText1, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.AndText1.text")); // NOI18N

        NameTextField.setText(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.NameTextField.text")); // NOI18N
        NameTextField.setEnabled(false);

        IdentifierTextField.setText(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.IdentifierTextField.text")); // NOI18N
        IdentifierTextField.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(RunButton, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.RunButton.text")); // NOI18N
        RunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunButtonActionPerformed(evt);
            }
        });

        HasLimitCheckBox.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(HasLimitCheckBox, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.HasLimitCheckBox.text")); // NOI18N
        HasLimitCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasLimitCheckBoxActionPerformed(evt);
            }
        });

        LimitTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        LimitTextField.setText(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.LimitTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(SourceNameTextLabel, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.SourceNameTextLabel.text")); // NOI18N
        SourceNameTextLabel.setOpaque(true);

        QueryNameTextField.setText(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.QueryNameTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(CreationYearLabel, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.CreationYearLabel.text")); // NOI18N
        CreationYearLabel.setToolTipText(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.CreationYearLabel.toolTipText")); // NOI18N

        CreationStartYearTextField.setText(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.CreationStartYearTextField.text")); // NOI18N

        CreationEndYearTextField.setText(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.CreationEndYearTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(HasDepictionCheckBox, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.HasDepictionCheckBox.text")); // NOI18N
        HasDepictionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasDepictionCheckBoxActionPerformed(evt);
            }
        });

        DepictionTextField.setText(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.DepictionTextField.text")); // NOI18N
        DepictionTextField.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(HasConsistsCheckBox, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.HasConsistsCheckBox.text")); // NOI18N
        HasConsistsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasConsistsCheckBoxActionPerformed(evt);
            }
        });

        MaterialTextField.setText(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.MaterialTextField.text")); // NOI18N
        MaterialTextField.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(HasTypeCheckBox, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.HasTypeCheckBox.text")); // NOI18N
        HasTypeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasTypeCheckBoxActionPerformed(evt);
            }
        });

        TypeTextField.setText(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.TypeTextField.text")); // NOI18N
        TypeTextField.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(HasTechniqueCheckBox, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.HasTechniqueCheckBox.text")); // NOI18N
        HasTechniqueCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HasTechniqueCheckBoxActionPerformed(evt);
            }
        });

        TechniqueTextField.setText(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.TechniqueTextField.text")); // NOI18N
        TechniqueTextField.setEnabled(false);

        javax.swing.GroupLayout QueriesLayout = new javax.swing.GroupLayout(Queries);
        Queries.setLayout(QueriesLayout);
        QueriesLayout.setHorizontalGroup(
            QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QueriesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ExistingQueriesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(QueriesLayout.createSequentialGroup()
                        .addComponent(DeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RunButton))
                    .addComponent(QueriesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QuerySeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VerticalSeparator)
                    .addGroup(QueriesLayout.createSequentialGroup()
                        .addComponent(QueryBuilderText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SourceNameTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(QueryNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QueriesLayout.createSequentialGroup()
                        .addGap(0, 493, Short.MAX_VALUE)
                        .addComponent(ResetButton)
                        .addGap(18, 18, 18)
                        .addComponent(CreateButton))
                    .addGroup(QueriesLayout.createSequentialGroup()
                        .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QueriesLayout.createSequentialGroup()
                                .addComponent(SourceTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SourceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(QueriesLayout.createSequentialGroup()
                                .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HasLimitCheckBox)
                                    .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(LimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(QueriesLayout.createSequentialGroup()
                                                .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(HasIdentifierCheckBox)
                                                    .addComponent(HasNameCheckBox)
                                                    .addComponent(HasDepictionCheckBox))
                                                .addGap(52, 52, 52)
                                                .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(NameTextField)
                                                        .addComponent(IdentifierTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(DepictionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(QueriesLayout.createSequentialGroup()
                                                .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(HasTypeCheckBox)
                                                    .addComponent(HasTechniqueCheckBox)
                                                    .addComponent(HasConsistsCheckBox)
                                                    .addComponent(CreationYearLabel))
                                                .addGap(22, 22, 22)
                                                .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(TypeTextField)
                                                    .addComponent(TechniqueTextField)
                                                    .addComponent(MaterialTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                                    .addComponent(CreationStartYearTextField))))))
                                .addGap(18, 18, 18)
                                .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HasImageCheckBox)
                                    .addGroup(QueriesLayout.createSequentialGroup()
                                        .addComponent(AndText1)
                                        .addGap(18, 18, 18)
                                        .addComponent(CreationEndYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 174, Short.MAX_VALUE)))
                .addContainerGap())
        );
        QueriesLayout.setVerticalGroup(
            QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QuerySeparator)
            .addGroup(QueriesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QueriesLayout.createSequentialGroup()
                        .addComponent(ExistingQueriesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QueriesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeleteButton)
                            .addComponent(RunButton)))
                    .addGroup(QueriesLayout.createSequentialGroup()
                        .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QueryBuilderText)
                            .addComponent(SourceNameTextLabel)
                            .addComponent(QueryNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VerticalSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SourceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SourceTextLabel))
                        .addGap(26, 26, 26)
                        .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CreationEndYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AndText1)
                            .addComponent(CreationStartYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CreationYearLabel))
                        .addGap(18, 18, 18)
                        .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HasNameCheckBox))
                        .addGap(18, 18, 18)
                        .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IdentifierTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HasIdentifierCheckBox))
                        .addGap(18, 18, 18)
                        .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DepictionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HasDepictionCheckBox))
                        .addGap(18, 18, 18)
                        .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaterialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HasConsistsCheckBox))
                        .addGap(18, 18, 18)
                        .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HasTypeCheckBox)
                            .addComponent(TypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HasTechniqueCheckBox)
                            .addComponent(TechniqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HasLimitCheckBox)
                            .addComponent(LimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HasImageCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(QueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CreateButton)
                            .addComponent(ResetButton))))
                .addContainerGap())
        );

        Tab.addTab(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.Queries.TabConstraints.tabTitle"), Queries); // NOI18N

        EntitiesScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        EntitiesTable.setAutoCreateRowSorter(true);
        EntitiesTable.setModel(new EntityTableModel(coll));
        EntitiesScrollPane.setViewportView(EntitiesTable);

        javax.swing.GroupLayout EntitiesLayout = new javax.swing.GroupLayout(Entities);
        Entities.setLayout(EntitiesLayout);
        EntitiesLayout.setHorizontalGroup(
            EntitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntitiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EntitiesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
                .addContainerGap())
        );
        EntitiesLayout.setVerticalGroup(
            EntitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntitiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EntitiesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tab.addTab(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.Entities.TabConstraints.tabTitle"), Entities); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(FirstFilterLabel, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.FirstFilterLabel.text")); // NOI18N
        FirstFilterLabel.setOpaque(true);

        FirstFilterComboBox.setModel(new DefaultComboBoxModel(categories.toArray()));
        FirstFilterComboBox.setToolTipText(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.FirstFilterComboBox.toolTipText")); // NOI18N
        FirstFilterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstFilterComboBoxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(Group1Label, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.Group1Label.text")); // NOI18N
        Group1Label.setOpaque(true);

        Group1ComboBox.setEnabled(false);
        Group1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Group1ComboBoxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(Group1FilterLabel, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.Group1FilterLabel.text")); // NOI18N
        Group1FilterLabel.setOpaque(true);

        Group1FilterComboBox.setEnabled(false);
        Group1FilterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Group1FilterComboBoxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(Group2Label, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.Group2Label.text")); // NOI18N
        Group2Label.setOpaque(true);

        Group2ComboBox.setEnabled(false);
        Group2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Group2ComboBoxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(Group2FilterLabel, org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.Group2FilterLabel.text")); // NOI18N
        Group2FilterLabel.setOpaque(true);

        Group2FilterComboBox.setEnabled(false);
        Group2FilterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Group2FilterComboBoxActionPerformed(evt);
            }
        });

        collectionDisplayPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout VisualizerLayout = new javax.swing.GroupLayout(Visualizer);
        Visualizer.setLayout(VisualizerLayout);
        VisualizerLayout.setHorizontalGroup(
            VisualizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisualizerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(FirstFilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FirstFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Group1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Group1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Group1FilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Group1FilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Group2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Group2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Group2FilterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Group2FilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(VisualizerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(collectionDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        VisualizerLayout.setVerticalGroup(
            VisualizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisualizerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(collectionDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VisualizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VisualizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Group2Label)
                        .addComponent(Group2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Group2FilterLabel)
                        .addComponent(Group2FilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VisualizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FirstFilterLabel)
                        .addComponent(FirstFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Group1Label)
                        .addComponent(Group1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Group1FilterLabel)
                        .addComponent(Group1FilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Tab.addTab(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.Visualizer.TabConstraints.tabTitle"), Visualizer); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tab)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.AccessibleContext.accessibleName")); // NOI18N
        getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(CollectionTopComponent.class, "CollectionTopComponent.AccessibleContext.accessibleDescription")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        resetQueryBuilder();
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        if(querySettingsAreValid()) {
            createQuery();
        }
    }//GEN-LAST:event_CreateButtonActionPerformed

    private void RunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunButtonActionPerformed
        if (coll.getQueriesCollection().getCount() > 0) {
            RequestProcessor executor = new RequestProcessor(coll.getName());
            try {
                etb.clearAll();
                EntitiesCollection entities = coll.getEntitiesCollection();
                
                Future<EntitiesCollection> result;
                
                Dispatcher dispatcher = new Dispatcher(coll.getQueriesCollection());
                result = executor.submit(dispatcher);
                
                EntitiesCollection newEntities;
                try
                {
                    newEntities = result.get();
                    entities.addThing(newEntities);
                }
                catch(InterruptedException | ExecutionException e){}
                
                entityModelChange();
                paintVisualDisplay(
                    etb.getFlattenedCollection(),
                    (String) FirstFilterComboBox.getSelectedItem()
                );
                
            } catch (HttpException ex) {
                output("502 Proxy Error: endpoint not available.");
            } finally {
                executor.shutdown();
            }
        } else {
            resetEntitiesAndDisplay();
            Tab.setSelectedIndex(TAB_VISUAL);
        }
    }//GEN-LAST:event_RunButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        int row = QueriesTable.getSelectedRow();
        if(row != -1) {
            String queryName;
            queryName = (String) qtb.getValueAt(row, qtb.findColumn("Name"));
            coll.getEntitiesCollection().removeQuery(queryName);
            qtb.deleteSource(row);
            entityModelChange();
            queryModelChange();
            paintVisualDisplay(
                etb.getFlattenedCollection(),
                (String) FirstFilterComboBox.getSelectedItem()
            );
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void TitleTextBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TitleTextBoxKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            coll.setName(TitleTextBox.getText());
            setName(coll.getName());
            NotesTextBox.requestFocus();
        }
    }//GEN-LAST:event_TitleTextBoxKeyReleased

    private void HasNameCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasNameCheckBoxActionPerformed
        if (HasNameCheckBox.isSelected()) {
            NameTextField.setEnabled(true);
        } else {
            NameTextField.setEnabled(false);
        }
    }//GEN-LAST:event_HasNameCheckBoxActionPerformed

    private void HasIdentifierCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasIdentifierCheckBoxActionPerformed
        if (HasIdentifierCheckBox.isSelected()) {
            IdentifierTextField.setEnabled(true);
        } else {
            IdentifierTextField.setEnabled(false);
        }
    }//GEN-LAST:event_HasIdentifierCheckBoxActionPerformed

    private void HasDepictionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasDepictionCheckBoxActionPerformed
        if (HasDepictionCheckBox.isSelected()) {
            DepictionTextField.setEnabled(true);
        } else {
            DepictionTextField.setEnabled(false);
        }
    }//GEN-LAST:event_HasDepictionCheckBoxActionPerformed

    private void HasConsistsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasConsistsCheckBoxActionPerformed
        if (HasConsistsCheckBox.isSelected()) {
            MaterialTextField.setEnabled(true);
        } else {
            MaterialTextField.setEnabled(false);
        }
    }//GEN-LAST:event_HasConsistsCheckBoxActionPerformed

    private void HasTypeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasTypeCheckBoxActionPerformed
        if (HasTypeCheckBox.isSelected()) {
            TypeTextField.setEnabled(true);
        } else {
            TypeTextField.setEnabled(false);
        }
    }//GEN-LAST:event_HasTypeCheckBoxActionPerformed

    private void HasTechniqueCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasTechniqueCheckBoxActionPerformed
        if (HasTechniqueCheckBox.isSelected()) {
            TechniqueTextField.setEnabled(true);
        } else {
            TechniqueTextField.setEnabled(false);
        }
    }//GEN-LAST:event_HasTechniqueCheckBoxActionPerformed

    private void HasLimitCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HasLimitCheckBoxActionPerformed
        if (HasLimitCheckBox.isSelected()) {
            LimitTextField.setEnabled(true);
        } else {
            LimitTextField.setEnabled(false);
        }
    }//GEN-LAST:event_HasLimitCheckBoxActionPerformed

    private void Group1ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Group1ComboBoxActionPerformed
        String selectedItem = (String) Group1ComboBox.getSelectedItem();
        if (selectedItem.equalsIgnoreCase("None")) {
            filterDisplay(
                true,
                false,
                false,
                (String) FirstFilterComboBox.getSelectedItem(),
                "",
                ""
            );
            setComboBoxes(
                    true,
                    false,
                    false,
                    false
            );
        } else {
            filterDisplay(
                true,
                true,
                false,
                (String) FirstFilterComboBox.getSelectedItem(),
                "",
                ""
            );
            setComboBoxes(
                    true,
                    true,
                    false,
                    false
            );
            ComboBoxModel comboModel = new DefaultComboBoxModel(categories.toArray());
            Group1FilterComboBox.setModel(comboModel);
        }
    }//GEN-LAST:event_Group1ComboBoxActionPerformed

    private void FirstFilterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstFilterComboBoxActionPerformed
        String selectedItem = (String) FirstFilterComboBox.getSelectedItem();
        String[] timelines = filterDisplay(
            true,
            false,
            false,
            selectedItem,
            "",
            ""
        );
        if (selectedItem.equalsIgnoreCase("None")) {
            setComboBoxes(
                    false,
                    false,
                    false,
                    false
            );
        } else {
            setComboBoxes(
                    true,
                    false,
                    false,
                    false
            );
            ComboBoxModel comboModel = new DefaultComboBoxModel(timelines);
            Group1ComboBox.setModel(comboModel);
        }
    }//GEN-LAST:event_FirstFilterComboBoxActionPerformed

    private void Group1FilterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Group1FilterComboBoxActionPerformed
        String selectedItem = (String) Group1FilterComboBox.getSelectedItem();
        String[] timelines = filterDisplay(
            true,
            true,
            false,
            (String) FirstFilterComboBox.getSelectedItem(),
            selectedItem,
            ""
        );
        if (selectedItem.equalsIgnoreCase("None")) {
            setComboBoxes(
                    true,
                    true,
                    false,
                    false
            );
        } else {
            setComboBoxes(
                    true,
                    true,
                    true,
                    false
            );
            ComboBoxModel comboModel = new DefaultComboBoxModel(timelines);
            Group2ComboBox.setModel(comboModel);
        }
    }//GEN-LAST:event_Group1FilterComboBoxActionPerformed

    private void Group2FilterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Group2FilterComboBoxActionPerformed
        String selectedItem = (String) Group2FilterComboBox.getSelectedItem();
        filterDisplay(
            true,
            true,
            true,
            (String) FirstFilterComboBox.getSelectedItem(),
            (String) Group1FilterComboBox.getSelectedItem(),
            selectedItem
        );
    }//GEN-LAST:event_Group2FilterComboBoxActionPerformed

    private void Group2ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Group2ComboBoxActionPerformed
        String selectedItem = (String) Group2ComboBox.getSelectedItem();
        if (selectedItem.equalsIgnoreCase("None")) {
            filterDisplay(
                true,
                true,
                false,
                (String) FirstFilterComboBox.getSelectedItem(),
                (String) Group1FilterComboBox.getSelectedItem(),
                ""
            );
            setComboBoxes(
                    true,
                    true,
                    true,
                    false
            );
        } else {
            filterDisplay(
                true,
                true,
                true,
                (String) FirstFilterComboBox.getSelectedItem(),
                (String) Group1FilterComboBox.getSelectedItem(),
                ""
            );
            setComboBoxes(
                    true,
                    true,
                    true,
                    true
            );
            ComboBoxModel comboModel = new DefaultComboBoxModel(categories.toArray());
            Group2FilterComboBox.setModel(comboModel);
        }
    }//GEN-LAST:event_Group2ComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AndText1;
    private javax.swing.JButton CreateButton;
    private javax.swing.JTextField CreationEndYearTextField;
    private javax.swing.JTextField CreationStartYearTextField;
    private javax.swing.JLabel CreationYearLabel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField DepictionTextField;
    private javax.swing.JPanel Entities;
    private javax.swing.JScrollPane EntitiesScrollPane;
    private javax.swing.JTable EntitiesTable;
    private javax.swing.JLabel ExistingQueriesText;
    private javax.swing.JComboBox<String> FirstFilterComboBox;
    private javax.swing.JLabel FirstFilterLabel;
    private javax.swing.JComboBox<String> Group1ComboBox;
    private javax.swing.JComboBox<String> Group1FilterComboBox;
    private javax.swing.JLabel Group1FilterLabel;
    private javax.swing.JLabel Group1Label;
    private javax.swing.JComboBox<String> Group2ComboBox;
    private javax.swing.JComboBox<String> Group2FilterComboBox;
    private javax.swing.JLabel Group2FilterLabel;
    private javax.swing.JLabel Group2Label;
    private javax.swing.JCheckBox HasConsistsCheckBox;
    private javax.swing.JCheckBox HasDepictionCheckBox;
    private javax.swing.JCheckBox HasIdentifierCheckBox;
    private javax.swing.JCheckBox HasImageCheckBox;
    private javax.swing.JCheckBox HasLimitCheckBox;
    private javax.swing.JCheckBox HasNameCheckBox;
    private javax.swing.JCheckBox HasTechniqueCheckBox;
    private javax.swing.JCheckBox HasTypeCheckBox;
    private javax.swing.JTextField IdentifierTextField;
    private javax.swing.JPanel Information;
    private javax.swing.JTextField LimitTextField;
    private javax.swing.JTextField MaterialTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel NotesText;
    private javax.swing.JTextArea NotesTextBox;
    private javax.swing.JScrollPane NotesTextPanel;
    private javax.swing.JPanel Queries;
    private javax.swing.JScrollPane QueriesScrollPane;
    private javax.swing.JTable QueriesTable;
    private javax.swing.JLabel QueryBuilderText;
    private javax.swing.JTextField QueryNameTextField;
    private javax.swing.JSeparator QuerySeparator;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton RunButton;
    private javax.swing.JComboBox<String> SourceComboBox;
    private javax.swing.JLabel SourceNameTextLabel;
    private javax.swing.JLabel SourceTextLabel;
    private javax.swing.JTabbedPane Tab;
    private javax.swing.JTextField TechniqueTextField;
    private javax.swing.JTextField TitleTextBox;
    private javax.swing.JTextField TypeTextField;
    private javax.swing.JSeparator VerticalSeparator;
    private javax.swing.JPanel Visualizer;
    private org.jghill.timelinesvisualizercollections.display.CollectionDisplayPanel collectionDisplayPanel;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    
    private final String none = "None";
    private final String query = "Query";
    private final String source = "Source";
    private final String depicts = "Depicts";
    private final String material = "Material";
    private final String type = "Type";
    private final String technique = "Technique";
    
    private final List<String> categories = new ArrayList<>();
    
    private static final int TAB_VISUAL = 3;
    
    private final EntityTableModel etb;
    private final QueryTableModel qtb;
    private final Collection coll;
    private final InstanceContent content = new InstanceContent();
    private final AbstractLookup abLookup = new AbstractLookup(content);
    private final Lookup.Result <Source> sources;
    
    @Override
    public void componentOpened() {
        setName(coll.getName());
        associateLookup(abLookup);
        queryModelChange();
        paintVisualDisplay(
                etb.getFlattenedCollection(),
                (String) FirstFilterComboBox.getSelectedItem()
        );
    }

    @Override
    public void componentClosed() {}

    void writeProperties(java.util.Properties p) {
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
    }
    
    /**
     * A getter for the collection to be returned from this top component.
     * 
     * @return the collection.
     */
    public Collection getCollection() {
        return coll;
    }
    
    /**
     * Resets the query building section of the GUI.
     */
    private void resetQueryBuilder() {
        
        SourceNameTextLabel.setText("");
        
        SourceComboBox.setSelectedIndex(0);
        QueryNameTextField.setText("");
        
        CreationEndYearTextField.setText("");
        CreationStartYearTextField.setText("");
        
        HasNameCheckBox.setSelected(false);
        NameTextField.setText("");
        NameTextField.setEnabled(false);
        
        HasIdentifierCheckBox.setSelected(false);
        IdentifierTextField.setText("");
        IdentifierTextField.setEnabled(false);
        
        HasDepictionCheckBox.setSelected(false);
        DepictionTextField.setText("");
        DepictionTextField.setEnabled(false);
        
        HasConsistsCheckBox.setSelected(false);
        MaterialTextField.setText("");
        MaterialTextField.setEnabled(false);
        
        HasTypeCheckBox.setSelected(false);
        TypeTextField.setText("");
        TypeTextField.setEnabled(false);
        
        HasTechniqueCheckBox.setSelected(false);
        TechniqueTextField.setText("");
        TechniqueTextField.setEnabled(false);
        
        HasLimitCheckBox.setSelected(true);
        LimitTextField.setText("10");
        LimitTextField.setEnabled(true);
        
        HasImageCheckBox.setSelected(false);
        
    }
    
    /**
     * Checks whether the query builder section has been filled correctly.
     * 
     * @return where it has been filled correctly.
     */
    private boolean querySettingsAreValid() {
        
        String startYear = CreationStartYearTextField.getText();
        if(startYear.length() > 4) {return false;}
        if(!Pattern.matches("[0-9]+", startYear) && !startYear.isEmpty()) {return false;}
        
        String endYear = CreationEndYearTextField.getText();
        if(endYear.length() > 4) {return false;}
        if(!Pattern.matches("[0-9]+", endYear) && !endYear.isEmpty()) {return false;}
        
        if(QueryNameTextField.getText().isEmpty()) {return false;}
        if(SourceComboBox.getSelectedItem() == null) {return false;}
        
        return true;
        
    }
    
    /**
     * Creates a query.
     */
    private void createQuery() {
        QuerySettings settings;
        settings = new QuerySettings(
                
                (Source) SourceComboBox.getSelectedItem(),
                QueryNameTextField.getText().trim(),
                
                CreationStartYearTextField.getText().trim().toLowerCase(),
                CreationEndYearTextField.getText().trim().toLowerCase(),
                
                HasNameCheckBox.isSelected(),
                NameTextField.getText().trim().toLowerCase(),
            
                HasIdentifierCheckBox.isSelected(),
                IdentifierTextField.getText().trim().toLowerCase(),
                
                HasDepictionCheckBox.isSelected(),
                DepictionTextField.getText().trim().toLowerCase(),
                
                HasConsistsCheckBox.isSelected(),
                MaterialTextField.getText().trim().toLowerCase(),
                
                HasTypeCheckBox.isSelected(),
                TypeTextField.getText().trim().toLowerCase(),
                
                HasTechniqueCheckBox.isSelected(),
                TechniqueTextField.getText().trim().toLowerCase(),
                
                HasLimitCheckBox.isSelected(),
                LimitTextField.getText().trim().toLowerCase(),
                
                HasImageCheckBox.isSelected()
                
        );
        QueryShell qry;
        QueryBuilder builder = QueryBuilder.getInstance();
        qry = builder.buildQuery(settings);
        coll.getQueriesCollection().addQuery(qry);
        resetQueryBuilder();
        queryModelChange();
    }
    
    /**
     * Fires changes to the query model table;
     */
    private void queryModelChange() {
        qtb.fireTableDataChanged();
    }
    
    /**
     * Fires changes to the entity model table;
     */
    private void entityModelChange() {
        etb.fireTableDataChanged();
    }
    
    /**
     * Outputs an explanation of the action.
     * 
     * @param text toString of the returned entity.
     */
    private void output(String text) {
        InputOutput io = IOProvider.getDefault().getIO("Main", false);
        io.getOut().println(text);
    }
    
    /**
     * Resets the entities collection and the collection display.
     */
    private void resetEntitiesAndDisplay() {
        etb.clearAll();
        collectionDisplayPanel.clear();
    }
    
    /**
     * Paints the visual display.
     */
    private String[] paintVisualDisplay(ManMadeObject[] collection, String filter) {
        TimeLine[] timelines;
        if (collection.length > 0) {
            timelines = collectionDisplayPanel.setArray(collection, filter);
            Tab.setSelectedIndex(TAB_VISUAL);
        } else {
            collectionDisplayPanel.clear();
            timelines = new TimeLine[0];
        }
        String[] timelineNames = new String[timelines.length + 1];
        timelineNames[0] = "None";
        for (int i = 1; i < timelineNames.length; i++) {
            timelineNames[i] = timelines[i-1].getName();
        }
        return timelineNames;
    }

    @Override
    public void focusGained(FocusEvent e) {
        EntityDisplay temp = (EntityDisplay) e.getSource();
        content.add(temp.getLookup().lookupResult(Entities.class).allInstances().iterator().next());
    }

    @Override
    public void focusLost(FocusEvent e) {
        EntityDisplay temp = (EntityDisplay) e.getSource();
        content.remove(temp.getLookup().lookupResult(Entities.class).allInstances().iterator().next());
    }
    
    /**
     * A getter for the First Filter combobox.
     * 
     * @return the First Filter comboBox.
     */
    public JComboBox<String> getFirstFilter() {
        return FirstFilterComboBox;
    }
    
    /**
     * Sets the status of the combo boxes.
     * 
     * @param combo1
     * @param filter1
     * @param combo2
     * @param filter2 
     */
    private void setComboBoxes(
            boolean combo1,
            boolean filter1,
            boolean combo2,
            boolean filter2
    ) {
        Group1ComboBox.setEnabled(combo1);
        Group1FilterComboBox.setEnabled(filter1);
        Group2ComboBox.setEnabled(combo2);
        Group2FilterComboBox.setEnabled(filter2);
    }
    
    /**
     * Filters the display to the correct level.
     * 
     * @param first level.
     * @param second level.
     * @param third level.
     * @param filter1 the term to filter with.
     * @param filter2 the term to filter with.
     * @param filter3 the term to filter with.
     */
    private String[] filterDisplay(
            boolean first,
            boolean second,
            boolean third,
            String filter1,
            String filter2,
            String filter3
    ) {
        String[] timelines = null;
        if (first) {
            timelines = paintVisualDisplay(
                etb.getFlattenedCollection(),
                filter1
            );
        }
        if (second) {
            timelines = paintVisualDisplay(
                collectionDisplayPanel.getTimeLine((String) Group1ComboBox.getSelectedItem()),
                filter2
            );
        }
        if (third) {
            timelines = paintVisualDisplay(
                collectionDisplayPanel.getTimeLine((String) Group2ComboBox.getSelectedItem()),
                filter3
            );
        }
        return timelines;
    }
    
}